### ISSUE TITLE
IE + XLSX Format support

### ISSUE THREAD

**Issue by chankeypathak** [rainabba/jquery-table2excel#1]
It doesn't work in IE10 and lower versions. Also there should be a way to download file in xlsx format.

**Comment by jzhang6** [comment]
Is this resolved? and any workaround for IE?

**Comment by rainabba** [comment]
This plugin is a hack and as such, isn't going to work in all browsers. As it stands, it will not work as intended in IE 11 on 8.1 because I'm not prompted to save, but instead it tries to open an associated app from the Windows Store.

I wouldn't even try to support IE9 given how old it is, but you're welcome to fork and add that support of course.

It does work in Chrome 44.
