### ISSUE TITLE
support for numbers with a leading "0"

### ISSUE THREAD

**Issue by benicillin** [rainabba/jquery-table2excel#16]
hi rain. is there any way to augment the code to add a flag to support columns that contain numbers, similar to the flag you use to exclude columns?

when you export a column with numbers that have a leading zero, excel trims the zero out of the code entirely when it opens. if we could augment those columns to add a few characters it would work correctly (where 000123 will show 123 in excel, ="000123" will show 000123 in excel).

**Comment by rainabba** [comment]
I'll add an attribute check for data-type where you can specify "string" to have the data stored as a string instead of the default ("General") that causes apparent numbers to be treated as numbers. Can't give you an ETA right now (and someone else could do this and submit a pull request of course) though.

**Comment by benicillin** [comment]
hey rain did you ever get around to this?

**Comment by benicillin** [comment]
pulled and added this feature
