### ISSUE TITLE
strange message about file format

### ISSUE THREAD

**Issue by AliveDD** [rainabba/jquery-table2excel#42]
im install plugin into my app with options:

        $("#restaurant_stat").table2excel({
            exclude: ".noExl",
            name: "SmartReserve",
            filename: xlsFilename,
            fileext: ".xls",
            exclude_img: false,
            exclude_links: false,
            exclude_inputs: false
        });

my table are converted, but on the run i have Strange message:

<img width="420" alt="screen shot 2016-06-21 at 20 10 14" src="https://cloud.githubusercontent.com/assets/5255027/16239168/b889428a-37f4-11e6-8280-2c2a5cfabb84.png">

help e please

**Comment by AliveDD** [comment]
hello?)

**Comment by rainabba** [comment]
Correct, because the files is an xlsx, but others have opted to change the extension provided by default in the code. Excel doesn't handle the file properly then either though (it's buggy) so really that message is "normal" given then approach.

Also, please understand that this isn't support. If you're going to post an issue, please first read the README at least. In this case I'd hope that you would take away that this is a hack and there are numerous issues inherent to it.

**Comment by AliveDD** [comment]
thanks, Now i find this warning in readme but this **heading** *threw me off* and I couldn't read more

<img width="938" alt="screen shot 2016-06-28 at 13 48 22" src="https://cloud.githubusercontent.com/assets/5255027/16412856/7d521f0c-3d3f-11e6-970b-117f1ab59e72.png">
