### ISSUE TITLE
UTF-8 Problem

### ISSUE THREAD

**Issue by erayaydin** [rainabba/jquery-table2excel#6]
Hello,
I have some turkish characters in HTML table. When I downloaded .xls table2excel file. Turkish characters looking bad/broken

**Comment by rainabba** [comment]
It definitely sounds like a unicode issue and I'm guessing that the html entity/escaped character (like &reg; or &#174;) doesn't work in Excel the same as in the browser and if that's the case, there's nothing I can do here. If you can copy/paste, then there's some hope, but the issue will likely be something I cannot support.

Can you copy/paste those same characters directly from the browser into Excel?

**Comment by ferman2147** [comment]
Hi @rainabba,
About @erayaydin's issue, I'm having the same problem. base4 decoding for Turkish characters such as "İ,ı,Ğ,ğ,ş,ç,ö..." doesn't work properly. How can we add a custom character replacing function to our table2exe.js file? Or is there any suggestion that you can give to solve this problem? (I think what we  need to enhance is around line 60 in the file. But I might very well be wrong beacuse I'm only a beginner in jQuery.)

**Comment by rainabba** [comment]
If you can confirm whether or not you can copy/paste those characters from the browser into Excel, then I'll better know what options might be available. My instinct says that something should be available to address this since multi-language unicode characters are common, but it's also not an area I have any real experience with in JS.

I wonder if this hints at the issue and possible solutions: http://stackoverflow.com/questions/60825/international-characters-in-javascript

**Comment by ferman2147** [comment]
Copying from browser to Excel is NOT the issue. Since Excel and all other office programs have Turkish language support, you can write those character directly to Excell, or copy/paste from anywhere. Here is a picture that shows characters are fine with Excel.
![adsiz](https://cloud.githubusercontent.com/assets/10866468/7214256/5b8cf658-e5ac-11e4-9b66-f7f1366565cc.png)

**Comment by ferman2147** [comment]
@erayaydin @rainabba I have finally found the solutions after trying everything I could.  In the table2excel.js file at line 29, where the head is defined  for e.template, I added this meta tag:
<meta http-equiv=\"content-type\" content=\"application/vnd.ms-excel; charset=UTF-8\">
right before <head>

**Comment by rainabba** [comment]
Thanks for the suggestion ferman2147. I just setup a rainabba-patch-utf8 branch but can't test yet so I created a pull request. If someone wants to try that branch and report back, I can commit to master quickly otherwise I will test when I can and commit then.

By the way, can I ask where you guys found out about my plugin? Suddenly it seems very popular :)

**Comment by erayaydin** [comment]
I tried manually (not branch) and its working!

**Comment by ferman2147** [comment]
Well, I'm working on a web based CRM for a company and they make quotation forms for customers, and they want it in excel. To this point, it's all great. I make them fill a contenteditable table, and  when they are finished they click on a button and magic! Excel is ready thanks to your plugin. But now they wanna view those excel forms (which they upload and store each URL in database) online when needed. That's where things go south for me :) I can't get the excel files created by your plugin to be readable. But I appreaciate your work. It's very useful.

**Comment by lomholdt** [comment]
I have tested @ferman2147's suggestion and it works perfectly. Definitely a good suggestion for merging to master.

**Comment by ignacio-chiazzo** [comment]
@ferman2147  I have tried with your hint but it doesn't work. 

I tried with this : 

In the table2excel I have :

e.template = {
				head: "<html xmlns:o=\"urn:schemas-microsoft-com:office:office\"  xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns=\"http://www.w3.org/TR/REC-html40\"><head></head><body>",
				table: {
					head: "<table>",
					tail: "</table>"
				},
				foot: "</body></html>"
			};

And below to the head tag I add the line which you says, but this doesn't work. The excel has not set utf-8

**Comment by Gaohaoyang** [comment]
@ferman2147 Thanks, it's worked in Chinese Charactor!

**Comment by GuvenAydin** [comment]
@ferman2147 Thank you bro

**Comment by monsieurchak** [comment]
@ferman2147 It works in Chinese! Thank you!

**Comment by ferman2147** [comment]
You're welcome guys.
@ignacio-chiazzo I'm sorry I haven't been aorund for a long time. In case you might still need help, I edited my comment, it's clearer now. You should add that above head tag, not below. I mean right before it, because above and below terms will need line break tweaks. Let's stick with "right before" :)

**Comment by Xiao-Ai** [comment]
@ferman2147 <met>a tag works perfect. Thanks, man!

**Comment by SahilGarg3shapes** [comment]
This doesn't work for me. I can copy russian language text to excel but when i export russian text it doesn't work.

I added below line before <head> tag and even tried after <head> tag as well but that doesn't work for me. See text "PASTED_MY_LINE_HERE" i replaced this text with below line.
"<meta http-equiv=\"content-type\" content=\"application/vnd.ms-excel; charset=UTF-8\">";


e.template = {
			    head: "<html xmlns:o=\"urn:schemas-microsoft-com:office:office\"  xmlns:x=\"urn:schemas-microsoft-com:office:excel\" xmlns=\"http://www.w3.org/TR/REC-html40\">PASTED_MY_LINE_HERE <head></head><body>",
			    table: {
			        head: "<table>",
			        tail: "</table>"
			    },
			    foot: "</body></html>"
			};



Please advice.

**Comment by Etchanty** [comment]
@ferman2147 it's working. I tried to complete it, Thank you
